services:
  unicard-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unicard-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - unicard-api

  unicard-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: unicard-api
    expose:
      - "5001"
    volumes:
      - ./data:/app/data
    restart: always
