server {
    listen 80;
    server_name localhost;

    # Gzip Compression
    gzip on;
    gzip_proxied any;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 1000;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Try finding files, then directories, then trailing slash index, and fallback to 404
        try_files $uri $uri/ $uri/index.html =404;
    }

    # Custom 404 fallback to Next.js exported 404 page
    error_page 404 /404/index.html;
    location = /404/index.html {
        root /usr/share/nginx/html;
        internal;
    }
}
